### ISSUE TITLE
Boss fight completamente rota

### ISSUE THREAD

**Issue by Ares75643** [Proyectos1-FDI-UCM/c2022-Grupo03#1]
Descripción
Es posible quitarle vida al boss y “matarlo” sin romperle ninguna pata, al hacerlo no termina de morir sino que se esconde en la parte superior del mapa y no vuelve a salir.

Pasos

1.     Entrar a la fase del boss.
2.     Seleccionar el color rojo en la ruleta de color.
3.     Disparar a la cabeza del boss con el rayo rojo. (al hacer esto el boss perderá casi toda su vida).
4.     Esperar a que se recargue la habilidad de rayo.
5.     Volver a disparar el rayo rojo a la cabeza del boss. (con esto el boss perderá toda su vida y pero no muere ni finaliza el nivel, el boss se retira hacia arriba y no vuelve a salir)
![IMG_20220427_102452](https://user-images.githubusercontent.com/92365761/165483683-ca76d1b6-3fdf-401b-bf21-c27f22f79dc4.jpg)

**Comment by P4179** [comment]
Solucionado!
