### ISSUE TITLE
Error visual en el boss

### ISSUE THREAD

**Issue by albpenal** [Proyectos1-FDI-UCM/c2022-Grupo03#10]
Descripción
En el nivel 3 del selector de niveles se puede observar como cada vez que la araña dispara durante un frame el aparece visualmente un proyectil hacia abajo, independientemente de donde se encuentre el jugador, pero este no hace daño, es solo visual.

Pasos
El fallo ocurre siempre que la araña dispara en el nivel 3 del selector de niveles.
Captura de pantalla o vídeo
Al ser solo un frame es complicado hacer una captura de ese momento.

**Comment by P4179** [comment]
Solucionado!
