### ISSUE TITLE
Enemigos bugeados

### ISSUE THREAD

**Issue by neutronbomb23** [Proyectos1-FDI-UCM/c2022-Grupo03#11]
### Descripción

Las ranas se quedan rebotando contra los pilares.

### Pasos 

1. Paso 1 Empiezas el nivel 1 y te sitúas cerca de algún pilar.
2. Paso 2 Esperas hasta que venga una rana hacía ti.
3. Paso 3 La rana se queda bugeada, es como si rebotase todo el rato contra el pilar.

### Captura de pantalla o vídeo

[![Texto alternativo](https://i9.ytimg.com/vi/2PoSZuNkSXM/mqdefault.jpg?sqp=CNj4qpMG&rs=AOn4CLBgyI0XV0lTGcbTPKx1xfKpH-kmTQ&retry=1)](https://youtu.be/2PoSZuNkSXM)

**Comment by frmolla** [comment]
Corregido
