### ISSUE TITLE
Kamikace sigue en pantalla despues de muerto

### ISSUE THREAD

**Issue by josepk01** [Proyectos1-FDI-UCM/c2022-Grupo03#12]
Kamikace sigue en pantalla despues de muerto
Descripción
Los Kamikace siguen en pantalla un segungo largo despues de haber explotado

Pasos
Paso 1 Te acercas al Kamikace
Paso 2 Este explota(Se ve poco la explosion)
Paso 3 Se queda un segundo en pantalla despues de muerto
Captura de pantalla o vídeo
https://drive.google.com/file/d/1zogA1QAupDY9s1qMRNn57q6V9RfqVMXl/view?usp=sharing

**Comment by frmolla** [comment]
Corregido
