### ISSUE TITLE
no diferenciacion verde y amarillo

### ISSUE THREAD

**Issue by josepk01** [Proyectos1-FDI-UCM/c2022-Grupo03#13]
no diferenciacion verde y amarillo
Descripción
En el nivel del boss las patas de la araña no se diferencian el amarillo y el verde si no aparece cuando luchas contra el la primera vez

Pasos
Paso 1 Pelear contra el boss
Paso 2 Que no aparezcan patas verdes

Captura de pantalla o vídeo
https://drive.google.com/file/d/1NBPzuAqaO7jLkWGaN3aUrV_jHMqxCYmM/view?usp=sharing
(en este caso si aparece el verde pero no lo veo de primeras y me confundo)

**Comment by marsache** [comment]
Arreglado
