### ISSUE TITLE
Bug en enemigo Melee

### ISSUE THREAD

**Issue by sosanc03** [Proyectos1-FDI-UCM/c2022-Grupo03#15]
Descripción: al probar el enemigo Melee en una ocasión hacía la animación de ataque, pero no ocasionaba ningún daño.
Pasos:
	Paso 1: pulsar “selector de niveles” en el menú principal.
	Paso 2: pulsar el enemigo Melee.
	(No ocurre todas las veces)
Vídeo: https://youtu.be/itp8COVffHs

**Comment by frmolla** [comment]
Corregido
