### ISSUE TITLE
Movimiento + Ataque

### ISSUE THREAD

**Issue by sosanc03** [Proyectos1-FDI-UCM/c2022-Grupo03#16]
Descripción: no existe la posibilidad de desplazarse cuando se está atacando que produce una gran dificultad para matar a los enemigos Range principalmente. También dificulta el huir si te confundes de color y estás atacando con el equivocado.
Pasos:
	Paso 1: pulsar en jugar.
	Paso 2: tratar de atacar mientras te mueves.
Vídeo: https://youtu.be/MkqtTcJfwYI

**Comment by P4179** [comment]
El ataque del jugador estaba pensado para que cuando lo realizara se parara. De todos modos, es muy útil el comentario y reduciremos el tiempo que se queda parado cuando realiza el ataque para que sea casi imperceptible.
