### ISSUE TITLE
Animación de los enemigos no tanques terrestres.

### ISSUE THREAD

**Issue by neutronbomb23** [Proyectos1-FDI-UCM/c2022-Grupo03#3]
### Descripción

La rana hace la animación de daño hacia los lados cuando el personaje principal está arriba
o abajo. Debería hacer la animación hacia arriba o abajo.

### Pasos 

• Paso 1 Me sitúo encima de cualquier enemigo que ataque cuerpo.
• Paso 2 Esperar hasta que el enemigo ataque.
• Paso 3 Ver que el enemigo no hace el ataque hacia arriba o hacia abajo.

**Comment by frmolla** [comment]
No es un error es una decisión de diseño, con el tamaño de las áreas laterales también se cubre arriba y abajo.
