### ISSUE TITLE
Imposible acabar el nivel del boss.

### ISSUE THREAD

**Issue by neutronbomb23** [Proyectos1-FDI-UCM/c2022-Grupo03#4]
### Descripción

Al decapitar la araña con el rayo rojo, esta sigue disparando telarañas, si te sitúas detrás de
él, las telarañas chocan contra su propio collider y desaparecen, tampoco hace daño de
contacto si me sitúo detrás de la araña.

### Pasos 

• Paso 1 Empiezas el nivel 3, seleccionando el color rojo.
• Paso 2 Te sitúas detrás de la araña.
• Paso 3 La telaraña no va a dar nunca al gato ya que la telaraña desaparece al chocar
contra su propio collider.

### Captura de pantalla o vídeo

(https://youtu.be/aEE0H_k9XNg) 
(https://youtu.be/6JcTHCrWnRA)

**Comment by P4179** [comment]
Solucionado!
