### ISSUE TITLE
Error del torbellino, funciona de vez en cuando con las patas de la araña.

### ISSUE THREAD

**Issue by neutronbomb23** [Proyectos1-FDI-UCM/c2022-Grupo03#6]
### Descripción

El torbellino no destruye las patas de la araña, también de vez en cuando actúa como escudo, evitando el daño del enemigo. 

### Pasos 
Paso 1 Entras en el nivel del boss. 
Paso 2 te sitúas detrás de la araña, activas el torbellino (ataque giratorio) con el color indicado y de la pata en cuestión

### Captura de pantalla o vídeo

(https://youtu.be/6OtA-m4Cgzc)

**Comment by P4179** [comment]
No se trata de un error técnico, sino de diseño porque estaba pensado que todas las patas de la araña tuvieran un solo punto de vida, pero las rosas tienen 2 y entonces no hay ningún aviso visual que indique que se le ha causado daño.
Se resolverá la equivocación y se reducirá la vida de todas las patas a 1 punto.
