### ISSUE TITLE
Sacar al enemigo a distancia del mapa

### ISSUE THREAD

**Issue by albpenal** [Proyectos1-FDI-UCM/c2022-Grupo03#7]
Descripción
El enemigo a distancia se puede sacar del mapa, aunque luego vuelve.

Pasos
Ejecutar el juego en cualquier nivel que haya enemigos que ataquen a distancia (en este caso en selector de niveles).
Empujar al enemigo moviéndote con tu propio personaje.
Realizar el paso 2 hacia una pared horizontal.

Captura de pantalla o vídeo
![a distancia en pared](https://user-images.githubusercontent.com/99793241/165734421-2eb41746-d2ee-4d9b-9bb1-34f5c028d1bb.PNG)

El enemigo está encima del personaje (píxeles rosas).

**Comment by frmolla** [comment]
Corregido
