### ISSUE TITLE
Fallo al no moverse en el nivel de test del enemigo cuerpo a cuerpo

### ISSUE THREAD

**Issue by albpenal** [Proyectos1-FDI-UCM/c2022-Grupo03#8]
Descripción
En el nivel de prueba del enemigo que ataca a melé (en el tanque también se puede replicar quitándole el escudo antes de que te llegue a mover) si no te mueves inicialmente el enemigo realiza la animación de ataque pero ni la vida ni el HUD se actualizan hasta que te muevas. Es decir si recibes dos golpes en el momento que te muevas el juego actualiza tu vida restándole lo correspondiente a dos golpes, si se reciben golpes suficientes para morir una vez te muevas morirás.

Pasos
Ejecutar en el selector de pruebas el nivel del enemigo melé o tanque.
No presionar WASD.
Esperar a que el enemigo te ataque (en caso del tanque hay que quitarle el escudo antes de que te llegue para que no te empuje, esto es posible con un rayo y dos ataques).

Captura de pantalla o vídeo
![no moverse](https://user-images.githubusercontent.com/99793241/165735207-5fe8ff0e-3561-428b-94f4-3dd0fc7010d4.PNG)
Se ve como el ataque ya se ha ejecutado pero la vida no se actualiza.

**Comment by frmolla** [comment]
Corregido
