### ISSUE TITLE
No aparecen enemigos

### ISSUE THREAD

**Issue by albpenal** [Proyectos1-FDI-UCM/c2022-Grupo03#9]
Descripción
En el nivel 1 del selector de niveles pueden no aparecer oleadas de enemigos.
Pasos
No he sido capaz de replicarlo, pero ha ocurrido al reaparecer en el nivel 1 tras morir, esperando varias veces los 15 segundos seguían sin aparecer enemigos.
Captura de pantalla o vídeo
![no aparecen enemigos](https://user-images.githubusercontent.com/99793241/165735607-e5b7444f-7e8c-453d-9d05-0032b0131c95.PNG)
Hay 0 enemigos y el tiempo ha llegado varias veces a 0.

**Comment by marsache** [comment]
Arreglado
